### ISSUE TITLE
Active window check error

### ISSUE THREAD

**Issue by Code-Mushy** [ANRAR4/AutoBTD6#12]
Traceback (most recent call last):                                                                                        File "C:\Users\Гриб\Downloads\AutoBTD6-main\replay.py", line 1230, in <module>                                            main()                                                                                                                File "C:\Users\Гриб\Downloads\AutoBTD6-main\replay.py", line 662, in main                                                 if not activeWindow or not isBTD6Window(activeWindow.title.decode()):                                               AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?

**Comment by ANRAR4** [comment]
Are you using AHK 2.0? The python ahk package currently only supports AHK 1.x (see #11).

In case this isn't the problem could you specify which version of python, AHK and python ahk you are using?

**Comment by Code-Mushy** [comment]
Yes, i Just removed `.decode()` and replaced `ahk.send_event()` with `ahk.send_input()` and that worked for me
