### ISSUE TITLE
Import Error for pyautogui

### ISSUE THREAD

**Issue by CobaltL** [ANRAR4/AutoBTD6#18]
$ python replay.py l
Traceback (most recent call last):
  File "C:\Users\Cobalt\Desktop\AutoBTD6-main\replay.py", line 1, in <module>
    from helper import *
  File "C:\Users\Cobalt\Desktop\AutoBTD6-main\helper.py", line 4, in <module>
    import pyautogui
  File "C:\Users\Cobalt\AppData\Roaming\Python\Python311\site-packages\pyautogui\__init__.py", line 542, in <module>
    from . import _pyautogui_win as platformModule
ImportError: cannot import name '_pyautogui_win' from partially initialized module 'pyautogui' (most likely due to a circular import) (C:\Users\Cobalt\AppData\Roaming\Python\Python311\site-packages\pyautogui\__init__.py)

I'm pretty certain this issue could be solved with experience in coding but I have none. Scowered and no solution was found. Could you please teach how to fix this?

**Comment by CobaltL** [comment]
Fixed import error for pyautogui by downgrading, fixed AHK by downgrading. Now this I have no idea how to fix. 
Traceback (most recent call last):
  File "C:\Users\Cobalt\Desktop\AutoBTD6-main\replay.py", line 1247, in <module>
    main()
  File "C:\Users\Cobalt\Desktop\AutoBTD6-main\replay.py", line 201, in main
    data = getResolutionDependentData()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cobalt\Desktop\AutoBTD6-main\replay.py", line 47, in getResolutionDependentData
    if getResolutionString(resolution) in rawSegmentCoordinates:
       ^^^^^^^^^^^^^^^^^^^
NameError: name 'getResolutionString' is not defined

**Comment by KendleMintJed** [comment]
This is an error with the pyautogui package versions 0.9.52 and above
downgrading to version 0.9.51 will fix the issue
