### ISSUE TITLE
no run 

### ISSUE THREAD

**Issue by kut2tjjj** [ANRAR4/AutoBTD6#23]
D:\Games\Bloons TD 6\AutoBTD6-main\AutoBTD6-main>py replay.py file dark_castle#chimps#2560x1440#noMK#noLL.btd6 -mk
D:\Games\Bloons TD 6\AutoBTD6-main\AutoBTD6-main\helper.py:20: SyntaxWarning: invalid escape sequence '\P'
  ahk = AHK(executable_path="D:\Python\python3.12\Scripts\AutoHotkey.exe")
D:\Games\Bloons TD 6\AutoBTD6-main\AutoBTD6-main\helper.py:122: SyntaxWarning: invalid escape sequence '\/'
  "^(?:(?:own_|unvalidated_|unsuccessful_)?playthroughs\/)?(?P<map>\w+)#(?P<gamemode>\w+)#(?P<resolution>(?P<resolution_x>\d+)x(?P<resolution_y>\d+))(?:#(?P<comment>.+))?\.btd6$",
D:\Games\Bloons TD 6\AutoBTD6-main\AutoBTD6-main\helper.py:318: SyntaxWarning: invalid escape sequence '\w'
  "^(?P<action>place|upgrade|retarget|special|sell|remove) ?(?P<type>[a-z_]+)? (?P<name>\w+)(?: (?:(?:at|to) (?P<x>\d+), (?P<y>\d+))?(?:path (?P<path>[0-2]))?)?(?: for (?P<price>\d+|\?\?\?))?(?: with (?P<discount>\d{1,2}|100)% discount)?$",
Traceback (most recent call last):
  File "D:\Games\Bloons TD 6\AutoBTD6-main\AutoBTD6-main\replay.py", line 1, in <module>
    from helper import *
  File "D:\Games\Bloons TD 6\AutoBTD6-main\AutoBTD6-main\helper.py", line 2, in <module>
    import keyboard
ModuleNotFoundError: No module named 'keyboard'

D:\Games\Bloons TD 6\AutoBTD6-main\AutoBTD6-main>

**Comment by kut2tjjj** [comment]
D:\Games\Bloons TD 6\AutoBTD6-main\AutoBTD6-main>py replay.py file dark_castle#chimps#2560x1440#noMK#noLL.btd6 -mk
D:\Games\Bloons TD 6\AutoBTD6-main\AutoBTD6-main\helper.py:122: SyntaxWarning: invalid escape sequence '\/'
  "^(?:(?:own_|unvalidated_|unsuccessful_)?playthroughs\/)?(?P<map>\w+)#(?P<gamemode>\w+)#(?P<resolution>(?P<resolution_x>\d+)x(?P<resolution_y>\d+))(?:#(?P<comment>.+))?\.btd6$",
D:\Games\Bloons TD 6\AutoBTD6-main\AutoBTD6-main\helper.py:318: SyntaxWarning: invalid escape sequence '\w'
  "^(?P<action>place|upgrade|retarget|special|sell|remove) ?(?P<type>[a-z_]+)? (?P<name>\w+)(?: (?:(?:at|to) (?P<x>\d+), (?P<y>\d+))?(?:path (?P<path>[0-2]))?)?(?: for (?P<price>\d+|\?\?\?))?(?: with (?P<discount>\d{1,2}|100)% discount)?$",
Traceback (most recent call last):
  File "D:\Games\Bloons TD 6\AutoBTD6-main\AutoBTD6-main\replay.py", line 1, in <module>
    from helper import *
  File "D:\Games\Bloons TD 6\AutoBTD6-main\AutoBTD6-main\helper.py", line 1338, in <module>
    version = float(fp.read())
                    ^^^^^^^^^
UnicodeDecodeError: 'gbk' codec can't decode byte 0xab in position 259: illegal multibyte sequence

D:\Games\Bloons TD 6\AutoBTD6-main\AutoBTD6-main>

**Comment by KendleMintJed** [comment]
It looks like your `version.txt` file is corrupted somehow. Try downloading a new one from the repo.
If that doesn't work, create a text document manually containing "43.0" and replace it with that.
