### ISSUE TITLE
record playthroughs error

### ISSUE THREAD

**Issue by Patrykosa** [ANRAR4/AutoBTD6#27]
C:\Users\USER\Documents\1\1\AutoBTD6-main>py record_playthrough.py
mapname >
dark_castle
gamemode >
deflation
hero >
obyn_greenfoot
started recording to "own_playthroughs/dark_castle#deflation#1920x1080.btd6"
place obyn_greenfoot hero0 at 547, 470
place super super0 738, 685
selected monkey: super0
BTD6 not focused
BTD6 not focused
stopping recording!
BTD6 not focused
Traceback (most recent call last):
  File "C:\Users\USER\Documents\1\1\AutoBTD6-main\record_playthrough.py", line 309, in <module>
    time.sleep(60)
  File "C:\Users\USER\Documents\1\1\AutoBTD6-main\record_playthrough.py", line 30, in signalHandler
    writeBTD6InstructionsFile(config)
  File "C:\Users\USER\Documents\1\1\AutoBTD6-main\helper.py", line 172, in writeBTD6InstructionsFile
    os.mkdir(folder)
FileNotFoundError: [WinError 2] The specified file could not be found: 'own_playthroughs'

**Comment by Patrykosa** [comment]
i figured it out
